package com.ems.services;

import java.util.ArrayList;
import java.util.List;

import javax.mail.MessagingException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ems.dao.CatererDao;
import com.ems.dao.EventDao;
import com.ems.dao.MenuDao;
import com.ems.dao.UserDao;
import com.ems.dao.VenueDao;
import com.ems.dto.EventDTO;
import com.ems.pojos.Event;
import com.ems.pojos.Menu;
import com.ems.pojos.Studio;
import com.ems.pojos.User;

@Service
@Transactional
public class EventServicesIMPL implements IEventServices {

	@Autowired
	MenuDao menuDao;
	@Autowired
	EventDao eventDao;
	@Autowired
	UserDao userDao;
	@Autowired
	VenueDao venueDao;
	@Autowired
	CatererDao catererDao;
	@Autowired
	private EmailSenderService mailservice;

	@Override
	public EventDTO registerEvent(EventDTO event, String email) {
		Event e = new Event(event.getName(), event.getType(), event.getDate(), event.getGuestCount(),
				event.isPhotography(), event.isVideography(), event.isAlbum(), event.isDrone(), event.isCrane(),
				event.getBookedVenue());
		e.setStatus("Waiting For Approval");
		User u = userDao.findByEmail(email).orElseThrow();
		u.getRegevents().add(e);
		List<Menu> menus = new ArrayList<Menu>();
		event.getMenus().forEach((p) -> menus.add(menuDao.findById(p.getId()).orElseThrow()));
		e.getMenus().addAll(menus);
		e.setCustomerEmail(email);
		String html1 = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n" + "<!--[if gte mso 9]>\r\n" + "<xml>\r\n" + "  <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG/>\r\n" + "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "  </o:OfficeDocumentSettings>\r\n" + "</xml>\r\n" + "<![endif]-->\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
				+ "  <title></title>\r\n" + "  \r\n" + "    <style type=\"text/css\">\r\n"
				+ "      @media only screen and (min-width: 620px) {\r\n" + "  .u-row {\r\n"
				+ "    width: 600px !important;\r\n" + "  }\r\n" + "  .u-row .u-col {\r\n"
				+ "    vertical-align: top;\r\n" + "  }\r\n" + "\r\n" + "  .u-row .u-col-100 {\r\n"
				+ "    width: 600px !important;\r\n" + "  }\r\n" + "\r\n" + "}\r\n" + "\r\n"
				+ "@media (max-width: 620px) {\r\n" + "  .u-row-container {\r\n" + "    max-width: 100% !important;\r\n"
				+ "    padding-left: 0px !important;\r\n" + "    padding-right: 0px !important;\r\n" + "  }\r\n"
				+ "  .u-row .u-col {\r\n" + "    min-width: 320px !important;\r\n"
				+ "    max-width: 100% !important;\r\n" + "    display: block !important;\r\n" + "  }\r\n"
				+ "  .u-row {\r\n" + "    width: calc(100% - 40px) !important;\r\n" + "  }\r\n" + "  .u-col {\r\n"
				+ "    width: 100% !important;\r\n" + "  }\r\n" + "  .u-col > div {\r\n" + "    margin: 0 auto;\r\n"
				+ "  }\r\n" + "}\r\n" + "body {\r\n" + "  margin: 0;\r\n" + "  padding: 0;\r\n" + "}\r\n" + "\r\n"
				+ "table,\r\n" + "tr,\r\n" + "td {\r\n" + "  vertical-align: top;\r\n"
				+ "  border-collapse: collapse;\r\n" + "}\r\n" + "\r\n" + "p {\r\n" + "  margin: 0;\r\n" + "}\r\n"
				+ "\r\n" + ".ie-container table,\r\n" + ".mso-container table {\r\n" + "  table-layout: fixed;\r\n"
				+ "}\r\n" + "\r\n" + "* {\r\n" + "  line-height: inherit;\r\n" + "}\r\n" + "\r\n"
				+ "a[x-apple-data-detectors='true'] {\r\n" + "  color: inherit !important;\r\n"
				+ "  text-decoration: none !important;\r\n" + "}\r\n" + "\r\n" + "@media (max-width: 480px) {\r\n"
				+ "  .hide-mobile {\r\n" + "    max-height: 0px;\r\n" + "    overflow: hidden;\r\n"
				+ "    display: none !important;\r\n" + "  }\r\n" + "\r\n" + "}\r\n"
				+ "table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-container-padding-padding { padding: 30px 10px 15px !important; } #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 52% !important; } #u_content_image_1 .v-text-align { text-align: center !important; } #u_row_2 .v-row-background-color { background-color: #000000 !important; } #u_row_2.v-row-background-color { background-color: #000000 !important; } #u_content_heading_1 .v-container-padding-padding { padding: 40px 10px 30px !important; } #u_content_button_2 .v-container-padding-padding { padding: 10px 10px 51px !important; } #u_content_button_2 .v-padding { padding: 10px 30px !important; } #u_row_8 .v-row-columns-background-color-background-color { background-color: #ffffff !important; } #u_content_image_5 .v-container-padding-padding { padding: 0px !important; } }\r\n"
				+ "    </style>\r\n" + "  \r\n" + "  \r\n" + "\r\n"
				+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><link href=\"https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
				+ "\r\n" + "</head>\r\n" + "\r\n"
				+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #fcf9f9;color: #000000\">\r\n"
				+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
				+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
				+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #fcf9f9;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "  <tbody>\r\n" + "  <tr style=\"vertical-align: top\">\r\n"
				+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
				+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #fcf9f9;\"><![endif]-->\r\n"
				+ "    \r\n" + "\r\n"
				+ "<div class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #000000;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-color: #000000;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_1\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:21px 10px 15px 50px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n" + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      <a href=\"https://unlayer.com\" target=\"_blank\">\r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/mqQjGK0/r661-Shubh-Karya-emblem-our.jpg\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 32%;max-width: 172.8px;\" width=\"172.8\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      </a>\r\n" + "    </td>\r\n" + "  </tr>\r\n" + "</table>\r\n" + "\r\n" + "      </td>\r\n"
				+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
				+ "<div id=\"u_row_2\" class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #000000;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-image: url('https://cdn.templates.unlayer.com/assets/1625308690936-839740');background-repeat: no-repeat;background-position: center top;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-image: url('images/image-4.jpeg');background-repeat: no-repeat;background-position: center top;background-color: #000000;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_heading_1\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h1 class=\"v-text-align\" style=\"margin: 0px; color: #ffffff; line-height: 170%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Raleway',sans-serif; font-size: 38px;\">\r\n"
				+ "    <strong>Event Booking Requested</strong>\r\n" + "  </h1>\r\n" + "\r\n" + "      </td>\r\n"
				+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 10px 20px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 180%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"line-height: 180%; font-size: 14px;\"><span style=\"font-family: Cabin, sans-serif; font-size: 14px; line-height: 25.2px;\"><span style=\"font-size: 16px; line-height: 28.8px;\">&nbsp; &nbsp;</span></span></p>\r\n"
				+ "  </div>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
				+ "\r\n"
				+ "<table id=\"u_content_button_2\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 50px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n" + "<div class=\"v-text-align\" align=\"center\">\r\n"
				+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;\"><tr><td class=\"v-text-align\" style=\"font-family:arial,helvetica,sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:44px; v-text-anchor:middle; width:305px;\" arcsize=\"34%\" stroke=\"f\" fillcolor=\"#ffffff\"><w:anchorlock/><center style=\"color:#333333;font-family:arial,helvetica,sans-serif;\"><![endif]-->\r\n"
				+ "    <a href=\"https://unlayer.com\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #333333; background-color: #ffffff; border-radius: 15px;-webkit-border-radius: 15px; -moz-border-radius: 15px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
				+ "      <span class=\"v-padding\" style=\"display:block;padding:10px 70px;line-height:120%;\"><span style=\"font-size: 20px; line-height: 24px;\"><strong>Wait for Approval</strong></span></span>\r\n"
				+ "    </a>\r\n" + "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
				+ "</div>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
				+ "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
				+ "<div id=\"u_row_8\" class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_5\" class=\"hide-mobile\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n" + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "    </td>\r\n" + "  </tr>\r\n" + "</table>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n"
				+ "  </tbody>\r\n" + "</table>\r\n" + "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
				+ "<div class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h1 class=\"v-text-align\" style=\"margin: 0px; color: #4e550e; line-height: 160%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Raleway',sans-serif; font-size: 37px;\">\r\n"
				+ "    We've Received Your Request&nbsp;\r\n" + "  </h1>\r\n" + "\r\n" + "      </td>\r\n"
				+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
				+ "<div class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n" + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td class=\"v-text-align\" style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "\r\n" + "    </td>\r\n" + "  </tr>\r\n" + "</table>\r\n" + "\r\n" + "      </td>\r\n"
				+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
				+ "<div class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #000000;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-color: #000000;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 10px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h1 class=\"v-text-align\" style=\"margin: 0px; color: #ffffff; line-height: 180%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Raleway',sans-serif; font-size: 28px;\">\r\n"
				+ "    You'll Receive Confirmation Mail Once Your Event is Approved,<br />Then You Can Proceed For the Payment\r\n"
				+ "  </h1>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
				+ "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
				+ "<div class=\"u-row-container v-row-background-color\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row v-row-columns-background-color-background-color\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #000000;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td class=\"v-row-background-color\" style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr class=\"v-row-columns-background-color-background-color\" style=\"background-color: #000000;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div class=\"v-text-align\" style=\"color: #ecf0f1; line-height: 180%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 180%;\"><span style=\"font-size: 14px; line-height: 25.2px; font-family: Montserrat, sans-serif;\">Want to change how you receive these emails? </span></p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 180%;\"><span style=\"font-size: 14px; line-height: 25.2px; font-family: Montserrat, sans-serif;\">You can update your preferences</span></p>\r\n"
				+ "  </div>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n" + "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div class=\"v-text-align\" style=\"color: #5f5c5c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"color: #ecf0f1; font-size: 14px; line-height: 19.6px;\">&copy; ShubhKaryaEvents. All Rights Reserved.</span></p>\r\n"
				+ "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\r\n" + "  </div>\r\n" + "\r\n"
				+ "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
				+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n"
				+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n" + "    </td>\r\n" + "  </tr>\r\n"
				+ "  </tbody>\r\n" + "  </table>\r\n" + "  <!--[if mso]></div><![endif]-->\r\n"
				+ "  <!--[if IE]></div><![endif]-->\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
		try {
			mailservice.sendMail(email, "Shubhkarya Event Registration", html1);
		} catch (MessagingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		return event;
	}

	@Override
	public Event updateEvent(EventDTO event, String email) {

		Event e = new Event(event.getName(), event.getType(), event.getDate(), event.getGuestCount(),
				event.isPhotography(), event.isVideography(), event.isAlbum(), event.isDrone(), event.isCrane(),
				event.getBookedVenue());
		e.setStudio(event.getStudio());
		e.setId(event.getId());
		e.setStatus(event.getStatus());
		e.setBookedCater(event.getBookedCater());
		e.setStudio(event.getStudio());
		e.setCustomerEmail(event.getCustomerEmail());
		List<Menu> menus = new ArrayList<Menu>();
		System.out.println(e);
		event.getMenus().forEach((p) -> menus.add(menuDao.findById(p.getId()).orElseThrow()));
		e.getMenus().addAll(menus);

		if (event.getStatus().equals("Waiting For Payment")) {
			double totalCost = 0;
			totalCost = e.getBookedVenue().getCost();
			Studio s = e.getStudio();
			if (e.isPhotography())
				totalCost += s.getPhotographycost();
			if (e.isVideography())
				totalCost += s.getVideographycost();
			if (e.isAlbum())
				totalCost += s.getAlbumcost();
			if (e.isDrone())
				totalCost += s.getDronecost();
			if (e.isCrane())
				totalCost += s.getCranecost();
			List<Menu> m = e.getMenus();
			for (Menu ms : m) {
				totalCost += (e.getGuestCount() * ms.getPrice());
			}
			e.setTotalCost(totalCost);
			System.out.println("TotalCost-" + e.getTotalCost());
			String html2 = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
					+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
					+ "<head>\r\n" + "<!--[if gte mso 9]>\r\n" + "<xml>\r\n" + "  <o:OfficeDocumentSettings>\r\n"
					+ "    <o:AllowPNG/>\r\n" + "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
					+ "  </o:OfficeDocumentSettings>\r\n" + "</xml>\r\n" + "<![endif]-->\r\n"
					+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
					+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
					+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
					+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
					+ "  <title></title>\r\n" + "  \r\n" + "    <style type=\"text/css\">\r\n"
					+ "      @media only screen and (min-width: 620px) {\r\n" + "  .u-row {\r\n"
					+ "    width: 600px !important;\r\n" + "  }\r\n" + "  .u-row .u-col {\r\n"
					+ "    vertical-align: top;\r\n" + "  }\r\n" + "\r\n" + "  .u-row .u-col-100 {\r\n"
					+ "    width: 600px !important;\r\n" + "  }\r\n" + "\r\n" + "}\r\n" + "\r\n"
					+ "@media (max-width: 620px) {\r\n" + "  .u-row-container {\r\n"
					+ "    max-width: 100% !important;\r\n" + "    padding-left: 0px !important;\r\n"
					+ "    padding-right: 0px !important;\r\n" + "  }\r\n" + "  .u-row .u-col {\r\n"
					+ "    min-width: 320px !important;\r\n" + "    max-width: 100% !important;\r\n"
					+ "    display: block !important;\r\n" + "  }\r\n" + "  .u-row {\r\n"
					+ "    width: calc(100% - 40px) !important;\r\n" + "  }\r\n" + "  .u-col {\r\n"
					+ "    width: 100% !important;\r\n" + "  }\r\n" + "  .u-col > div {\r\n" + "    margin: 0 auto;\r\n"
					+ "  }\r\n" + "}\r\n" + "body {\r\n" + "  margin: 0;\r\n" + "  padding: 0;\r\n" + "}\r\n" + "\r\n"
					+ "table,\r\n" + "tr,\r\n" + "td {\r\n" + "  vertical-align: top;\r\n"
					+ "  border-collapse: collapse;\r\n" + "}\r\n" + "\r\n" + "p {\r\n" + "  margin: 0;\r\n" + "}\r\n"
					+ "\r\n" + ".ie-container table,\r\n" + ".mso-container table {\r\n" + "  table-layout: fixed;\r\n"
					+ "}\r\n" + "\r\n" + "* {\r\n" + "  line-height: inherit;\r\n" + "}\r\n" + "\r\n"
					+ "a[x-apple-data-detectors='true'] {\r\n" + "  color: inherit !important;\r\n"
					+ "  text-decoration: none !important;\r\n" + "}\r\n" + "\r\n"
					+ "table, td { color: #000000; } a { color: #01499d; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 59% !important; } #u_content_image_2 .v-src-width { width: 100% !important; } #u_content_image_2 .v-src-max-width { max-width: 100% !important; } #u_content_heading_1 .v-container-padding-padding { padding: 20px !important; } #u_content_heading_1 .v-font-size { font-size: 23px !important; } #u_content_text_2 .v-container-padding-padding { padding: 40px 30px 50px 15px !important; } #u_content_button_1 .v-size-width { width: 81% !important; } }\r\n"
					+ "    </style>\r\n" + "  \r\n" + "  \r\n" + "\r\n"
					+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><link href=\"https://fonts.googleapis.com/css?family=Rubik:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
					+ "\r\n" + "</head>\r\n" + "\r\n"
					+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #e7e7e7;color: #000000\">\r\n"
					+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
					+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
					+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #e7e7e7;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "  <tbody>\r\n" + "  <tr style=\"vertical-align: top\">\r\n"
					+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
					+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #e7e7e7;\"><![endif]-->\r\n"
					+ "    \r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #1a2e35;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #1a2e35;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table id=\"u_content_image_1\" style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n" + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
					+ "  <tr>\r\n" + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
					+ "      <a href=\"unlayer,com\" target=\"_blank\">\r\n"
					+ "      <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/mqQjGK0/r661-Shubh-Karya-emblem-our.jpg\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 29%;max-width: 168.2px;\" width=\"168.2\" class=\"v-src-width v-src-max-width\"/>\r\n"
					+ "      </a>\r\n" + "    </td>\r\n" + "  </tr>\r\n" + "</table>\r\n" + "\r\n" + "      </td>\r\n"
					+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 0px 10px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 4px solid #037bfe;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "    <tbody>\r\n" + "      <tr style=\"vertical-align: top\">\r\n"
					+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "          <span>&#160;</span>\r\n" + "        </td>\r\n" + "      </tr>\r\n" + "    </tbody>\r\n"
					+ "  </table>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n"
					+ "</table>\r\n" + "\r\n"
					+ "<table id=\"u_content_image_2\" style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 0px 30px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n" + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
					+ "  <tr>\r\n" + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
					+ "      \r\n"
					+ "      <img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1636780637744-sdsds.png\" alt=\"Hero Image\" title=\"Hero Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 88%;max-width: 528px;\" width=\"528\" class=\"v-src-width v-src-max-width\"/>\r\n"
					+ "      \r\n" + "    </td>\r\n" + "  </tr>\r\n" + "</table>\r\n" + "\r\n" + "      </td>\r\n"
					+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #01499d;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #01499d;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table id=\"u_content_heading_1\" style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:20px 25px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <h1 class=\"v-font-size\" style=\"margin: 0px; color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: 'Raleway',sans-serif; font-size: 40px;\">\r\n"
					+ "    <strong>Event Approved</strong>\r\n" + "  </h1>\r\n" + "\r\n" + "      </td>\r\n"
					+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f5f5f5;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f5f5f5;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"598\" style=\"width: 598px;padding: 0px;border-top: 1px solid #CCC;border-left: 1px solid #CCC;border-right: 1px solid #CCC;border-bottom: 1px solid #CCC;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 1px solid #CCC;border-left: 1px solid #CCC;border-right: 1px solid #CCC;border-bottom: 1px solid #CCC;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table id=\"u_content_text_2\" style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"color: #5c5c5c; line-height: 170%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"font-size: 14px; line-height: 170%;\">&nbsp; &nbsp; &nbsp; &nbsp;</p>\r\n"
					+ "  </div>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
					+ "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #01499d;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #01499d;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table id=\"u_content_button_1\" style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:35px 10px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n" + "<div align=\"center\">\r\n"
					+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Rubik',sans-serif;\"><tr><td style=\"font-family:'Rubik',sans-serif;\" align=\"center\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://unlayer.com\" style=\"height:148px; v-text-anchor:middle; width:487px;\" arcsize=\"0%\" strokecolor=\"#ffffff\" strokeweight=\"3px\" fillcolor=\"#01499d\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Rubik',sans-serif;\"><![endif]-->\r\n"
					+ "    <a href=\"https://unlayer.com\" target=\"_blank\" class=\"v-size-width\" style=\"box-sizing: border-box;display: inline-block;font-family:'Rubik',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #01499d; border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px; width:85%; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-color: #ffffff; border-top-style: solid; border-top-width: 3px; border-left-color: #ffffff; border-left-style: solid; border-left-width: 3px; border-right-color: #ffffff; border-right-style: solid; border-right-width: 3px; border-bottom-color: #ffffff; border-bottom-style: solid; border-bottom-width: 3px;\">\r\n"
					+ "      <span style=\"display:block;padding:16px 20px;line-height:120%;\"><span style=\"font-size: 32px; line-height: 38.4px;\"><strong><span style=\"line-height: 38.4px; font-family: Raleway, sans-serif; font-size: 32px;\">You Can Proceed for the Payment to Confirm your Booking</span></strong></span></span>\r\n"
					+ "    </a>\r\n" + "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
					+ "</div>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
					+ "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 0px 20px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 4px solid #1a2e35;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "    <tbody>\r\n" + "      <tr style=\"vertical-align: top\">\r\n"
					+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "          <span>&#160;</span>\r\n" + "        </td>\r\n" + "      </tr>\r\n" + "    </tbody>\r\n"
					+ "  </table>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n"
					+ "</table>\r\n" + "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n" + "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
					+ "  <tr>\r\n" + "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
					+ "      \r\n"
					+ "      <img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1636783607482-dfdfdf.png\" alt=\"curve border\" title=\"curve border\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 600px;\" width=\"600\" class=\"v-src-width v-src-max-width\"/>\r\n"
					+ "      \r\n" + "    </td>\r\n" + "  </tr>\r\n" + "</table>\r\n" + "\r\n" + "      </td>\r\n"
					+ "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n" + "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n" + "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #1a2e35;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #1a2e35;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;border-radius: 0px;-webkit-border-radius: 0px; -moz-border-radius: 0px;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Rubik',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n" + "    <tr>\r\n"
					+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 44px 35px;font-family:'Rubik',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"color: #ecf0f1; line-height: 180%; text-align: center; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"font-size: 14px; line-height: 180%;\"><span style=\"font-family: Raleway, sans-serif; font-size: 14px; line-height: 25.2px;\">You're receiving this email because you asked us about regular updates.</span></p>\r\n"
					+ "<p style=\"font-size: 14px; line-height: 180%;\">@ShubhKaryaEvents. All rights reserved.</p>\r\n"
					+ "  </div>\r\n" + "\r\n" + "      </td>\r\n" + "    </tr>\r\n" + "  </tbody>\r\n" + "</table>\r\n"
					+ "\r\n" + "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n" + "  </div>\r\n" + "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n" + "    </div>\r\n"
					+ "  </div>\r\n" + "</div>\r\n" + "\r\n" + "\r\n"
					+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n" + "    </td>\r\n" + "  </tr>\r\n"
					+ "  </tbody>\r\n" + "  </table>\r\n" + "  <!--[if mso]></div><![endif]-->\r\n"
					+ "  <!--[if IE]></div><![endif]-->\r\n" + "</body>\r\n" + "\r\n" + "</html>\r\n" + "";
			try {
				mailservice.sendMail(event.getCustomerEmail(), "Your Event is Approved", html2);
			} catch (MessagingException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		} else if (event.getStatus().equals("Approved")) {
			e.setTotalCost(event.getTotalCost());
			if (event.getTotalCost() != 0) {
				String html3 = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
						+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
						+ "<head>\r\n"
						+ "<!--[if gte mso 9]>\r\n"
						+ "<xml>\r\n"
						+ "  <o:OfficeDocumentSettings>\r\n"
						+ "    <o:AllowPNG/>\r\n"
						+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
						+ "  </o:OfficeDocumentSettings>\r\n"
						+ "</xml>\r\n"
						+ "<![endif]-->\r\n"
						+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
						+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
						+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
						+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
						+ "  <title></title>\r\n"
						+ "  \r\n"
						+ "    <style type=\"text/css\">\r\n"
						+ "      @media only screen and (min-width: 620px) {\r\n"
						+ "  .u-row {\r\n"
						+ "    width: 600px !important;\r\n"
						+ "  }\r\n"
						+ "  .u-row .u-col {\r\n"
						+ "    vertical-align: top;\r\n"
						+ "  }\r\n"
						+ "\r\n"
						+ "  .u-row .u-col-100 {\r\n"
						+ "    width: 600px !important;\r\n"
						+ "  }\r\n"
						+ "\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ "@media (max-width: 620px) {\r\n"
						+ "  .u-row-container {\r\n"
						+ "    max-width: 100% !important;\r\n"
						+ "    padding-left: 0px !important;\r\n"
						+ "    padding-right: 0px !important;\r\n"
						+ "  }\r\n"
						+ "  .u-row .u-col {\r\n"
						+ "    min-width: 320px !important;\r\n"
						+ "    max-width: 100% !important;\r\n"
						+ "    display: block !important;\r\n"
						+ "  }\r\n"
						+ "  .u-row {\r\n"
						+ "    width: calc(100% - 40px) !important;\r\n"
						+ "  }\r\n"
						+ "  .u-col {\r\n"
						+ "    width: 100% !important;\r\n"
						+ "  }\r\n"
						+ "  .u-col > div {\r\n"
						+ "    margin: 0 auto;\r\n"
						+ "  }\r\n"
						+ "}\r\n"
						+ "body {\r\n"
						+ "  margin: 0;\r\n"
						+ "  padding: 0;\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ "table,\r\n"
						+ "tr,\r\n"
						+ "td {\r\n"
						+ "  vertical-align: top;\r\n"
						+ "  border-collapse: collapse;\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ "p {\r\n"
						+ "  margin: 0;\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ ".ie-container table,\r\n"
						+ ".mso-container table {\r\n"
						+ "  table-layout: fixed;\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ "* {\r\n"
						+ "  line-height: inherit;\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ "a[x-apple-data-detectors='true'] {\r\n"
						+ "  color: inherit !important;\r\n"
						+ "  text-decoration: none !important;\r\n"
						+ "}\r\n"
						+ "\r\n"
						+ "table, td { color: #000000; } @media (max-width: 480px) { #u_content_text_2 .v-line-height { line-height: 110% !important; } }\r\n"
						+ "    </style>\r\n"
						+ "  \r\n"
						+ "  \r\n"
						+ "\r\n"
						+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
						+ "\r\n"
						+ "</head>\r\n"
						+ "\r\n"
						+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #020202;color: #000000\">\r\n"
						+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
						+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
						+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #020202;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
						+ "  <tbody>\r\n"
						+ "  <tr style=\"vertical-align: top\">\r\n"
						+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
						+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #020202;\"><![endif]-->\r\n"
						+ "    \r\n"
						+ "\r\n"
						+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
						+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
						+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
						+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
						+ "      \r\n"
						+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
						+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
						+ "  <div style=\"width: 100% !important;\">\r\n"
						+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
						+ "  \r\n"
						+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
						+ "  <tbody>\r\n"
						+ "    <tr>\r\n"
						+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 21px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
						+ "        \r\n"
						+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
						+ "  <tr>\r\n"
						+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
						+ "      \r\n"
						+ "      <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/mqQjGK0/r661-Shubh-Karya-emblem-our.jpg\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 31%;max-width: 179.8px;\" width=\"179.8\"/>\r\n"
						+ "      \r\n"
						+ "    </td>\r\n"
						+ "  </tr>\r\n"
						+ "</table>\r\n"
						+ "\r\n"
						+ "      </td>\r\n"
						+ "    </tr>\r\n"
						+ "  </tbody>\r\n"
						+ "</table>\r\n"
						+ "\r\n"
						+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
						+ "  </div>\r\n"
						+ "</div>\r\n"
						+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
						+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
						+ "    </div>\r\n"
						+ "  </div>\r\n"
						+ "</div>\r\n"
						+ "\r\n"
						+ "\r\n"
						+ "\r\n"
						+ "<div class=\"u-row-container\" style=\"padding: 0px;background-image: url('https://cdn.templates.unlayer.com/assets/1620406878226-EE.jpg');background-repeat: no-repeat;background-position: center top;background-color: transparent\">\r\n"
						+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
						+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
						+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-image: url('https://cdn.templates.unlayer.com/assets/1620406878226-EE.jpg');background-repeat: no-repeat;background-position: center top;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
						+ "      \r\n"
						+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
						+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
						+ "  <div style=\"width: 100% !important;\">\r\n"
						+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
						+ "  \r\n"
						+ "<table id=\"u_content_text_2\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
						+ "  <tbody>\r\n"
						+ "    <tr>\r\n"
						+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
						+ "        \r\n"
						+ "  <div class=\"v-line-height\" style=\"color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
						+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 44px; line-height: 61.6px;\"><strong><span style=\"font-family: Cabin, sans-serif; line-height: 61.6px; font-size: 44px;\">Booking Successful</span></strong></span></p>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "      </td>\r\n"
						+ "    </tr>\r\n"
						+ "  </tbody>\r\n"
						+ "</table>\r\n"
						+ "\r\n"
						+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
						+ "  <tbody>\r\n"
						+ "    <tr>\r\n"
						+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
						+ "        \r\n"
						+ "  <div class=\"v-line-height\" style=\"color: #e9e9e9; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
						+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 44px; line-height: 61.6px; font-family: tahoma, arial, helvetica, sans-serif;\"><strong>"+event.getName()+"</strong></span></p>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "      </td>\r\n"
						+ "    </tr>\r\n"
						+ "  </tbody>\r\n"
						+ "</table>\r\n"
						+ "\r\n"
						+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
						+ "  <tbody>\r\n"
						+ "    <tr>\r\n"
						+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px 45px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
						+ "        \r\n"
						+ "  <div class=\"v-line-height\" style=\"color: #dbdbdb; line-height: 160%; text-align: center; word-wrap: break-word;\">\r\n"
						+ "    <p style=\"font-size: 14px; line-height: 160%;\"><span style=\"font-size: 20px; line-height: 32px;\">Dear Customer, Your Event is Booked Successfully</span><br /><span style=\"font-size: 20px; line-height: 32px;\">And We're Moving Ahead Towards Event Planning<br /></span><span style=\"font-size: 20px; line-height: 32px;\">To Make Your Event More Memorable</span><br /><br /></p>\r\n"
						+ "<p style=\"font-size: 14px; line-height: 160%;\"><span style=\"color: #ecf0f1; font-size: 32px; line-height: 51.2px;\"><strong><span style=\"line-height: 51.2px; font-size: 32px;\">WE CREATE, YOU CELEBRATE.</span></strong></span></p>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "      </td>\r\n"
						+ "    </tr>\r\n"
						+ "  </tbody>\r\n"
						+ "</table>\r\n"
						+ "\r\n"
						+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
						+ "  </div>\r\n"
						+ "</div>\r\n"
						+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
						+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
						+ "    </div>\r\n"
						+ "  </div>\r\n"
						+ "</div>\r\n"
						+ "\r\n"
						+ "\r\n"
						+ "\r\n"
						+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
						+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
						+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
						+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
						+ "      \r\n"
						+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
						+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
						+ "  <div style=\"width: 100% !important;\">\r\n"
						+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
						+ "  \r\n"
						+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
						+ "  <tbody>\r\n"
						+ "    <tr>\r\n"
						+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 35px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
						+ "        \r\n"
						+ "  <div class=\"v-line-height\" style=\"color: #727272; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
						+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"color: #ecf0f1; font-size: 14px; line-height: 19.6px;\">@ShubhKaryaEvents. All rights reserved.</span></p>\r\n"
						+ "  </div>\r\n"
						+ "\r\n"
						+ "      </td>\r\n"
						+ "    </tr>\r\n"
						+ "  </tbody>\r\n"
						+ "</table>\r\n"
						+ "\r\n"
						+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
						+ "  </div>\r\n"
						+ "</div>\r\n"
						+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
						+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
						+ "    </div>\r\n"
						+ "  </div>\r\n"
						+ "</div>\r\n"
						+ "\r\n"
						+ "\r\n"
						+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
						+ "    </td>\r\n"
						+ "  </tr>\r\n"
						+ "  </tbody>\r\n"
						+ "  </table>\r\n"
						+ "  <!--[if mso]></div><![endif]-->\r\n"
						+ "  <!--[if IE]></div><![endif]-->\r\n"
						+ "</body>\r\n"
						+ "\r\n"
						+ "</html>\r\n"
						+ "";
				try {
					mailservice.sendMail(event.getCustomerEmail(), "Your Event is Booked", html3);
				} catch (MessagingException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}

			}
		}else {
			e.setTotalCost(event.getTotalCost());
		}
		eventDao.save(e);
		return e;
	}

	@Override
	public List<Event> getByUsers(String email) {
		System.out.println(email);
		User u = userDao.findByEmail(email).orElseThrow();
		if (u.getRole().equals("ADMIN")) {
			return eventDao.findAll();
		} else
			return u.getRegevents();
	}

	@Override
	public Event getById(int id) {
		System.out.println(eventDao.getById(id));
		return eventDao.getById(id);
	}

	@Override
	public void assignEmployee(int id, User user) {
		System.out.println("in assemp");
		user.getRegevents().add(getById(id));
		System.out.println("in assemp mid");
		userDao.save(user);
		System.out.println("in assign end");
		String html4="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "<!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "  <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG/>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "  </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]-->\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
				+ "  <title></title>\r\n"
				+ "  \r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "      @media only screen and (min-width: 620px) {\r\n"
				+ "  .u-row {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    vertical-align: top;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col-100 {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "@media (max-width: 620px) {\r\n"
				+ "  .u-row-container {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    padding-left: 0px !important;\r\n"
				+ "    padding-right: 0px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    display: block !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row {\r\n"
				+ "    width: calc(100% - 40px) !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col > div {\r\n"
				+ "    margin: 0 auto;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "body {\r\n"
				+ "  margin: 0;\r\n"
				+ "  padding: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table,\r\n"
				+ "tr,\r\n"
				+ "td {\r\n"
				+ "  vertical-align: top;\r\n"
				+ "  border-collapse: collapse;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "p {\r\n"
				+ "  margin: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".ie-container table,\r\n"
				+ ".mso-container table {\r\n"
				+ "  table-layout: fixed;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "* {\r\n"
				+ "  line-height: inherit;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a[x-apple-data-detectors='true'] {\r\n"
				+ "  color: inherit !important;\r\n"
				+ "  text-decoration: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table, td { color: #000000; } a { color: #0000ee; text-decoration: underline; } @media (max-width: 480px) { #u_content_image_2 .v-src-width { width: auto !important; } #u_content_image_2 .v-src-max-width { max-width: 64% !important; } }\r\n"
				+ "    </style>\r\n"
				+ "  \r\n"
				+ "  \r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #f3f3f3;color: #000000\">\r\n"
				+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
				+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
				+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #f3f3f3;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "  <tr style=\"vertical-align: top\">\r\n"
				+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
				+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #f3f3f3;\"><![endif]-->\r\n"
				+ "    \r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:20px 10px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/mqQjGK0/r661-Shubh-Karya-emblem-our.jpg\" alt=\"Logo\" title=\"Logo\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 37%;max-width: 214.6px;\" width=\"214.6\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #577b27;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #577b27;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_2\" style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px 10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1627017618297-loudspeaker-1459128_960_720.png\" alt=\"Hero Image\" title=\"Hero Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 54%;max-width: 313.2px;\" width=\"313.2\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #fdfdfd; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 140%;\"><strong><span style=\"font-size: 40px; line-height: 56px;\">NEW EVENT ASSIGNED</span></strong></p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px 20px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #fdfdfd; line-height: 170%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 170%;\"><span style=\"font-size: 20px; line-height: 34px;\">For More Details Please Check on Portal</span></p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #eaffe4;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #eaffe4;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 50px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #727272; line-height: 170%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 170%;\"><span style=\"font-size: 18px; line-height: 30.6px;\">@ShubhKaryaEvents. All rights reserved.</span></p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #577b27;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #577b27;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 30px;font-family:arial,helvetica,sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<div class=\"menu\" style=\"text-align:center\">\r\n"
				+ "<!--[if (mso)|(IE)]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\"><tr><![endif]-->\r\n"
				+ "\r\n"
				+ "  <!--[if (mso)|(IE)]><td style=\"padding:5px 10px\"><![endif]-->\r\n"
				+ "  \r\n"
				+ "    <a href=\"https://unlayer.com/\" target=\"_self\" style=\"padding:5px 10px;display:inline-block;color:#ffffff;font-family:arial,helvetica,sans-serif;font-size:19px;text-decoration:none\" >\r\n"
				+ "      Contact : shubhkaryaaevents.off@gmail.com\r\n"
				+ "    </a>\r\n"
				+ "  \r\n"
				+ "  <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "  \r\n"
				+ "\r\n"
				+ "<!--[if (mso)|(IE)]></tr></table><![endif]-->\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "  </table>\r\n"
				+ "  <!--[if mso]></div><![endif]-->\r\n"
				+ "  <!--[if IE]></div><![endif]-->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>\r\n"
				+ "";
		try {
			mailservice.sendMail(user.getEmail(), "New Event Assigned", html4);
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public void unassignEmployee(int id, User user) {
		user.getRegevents().remove(getById(id));
		userDao.save(user);
	}

}
