package com.ems.services;

import java.util.List;

import javax.mail.MessagingException;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ems.dao.EventDao;
import com.ems.dao.UserDao;
import com.ems.dto.RegisterDTO;
import com.ems.pojos.Event;
import com.ems.pojos.User;

@Service
@Transactional
public class UserServicesIMPL implements IUserServices {

	@Autowired
	private UserDao userDao;
	
	@Autowired
	private  EmailSenderService mailservice;

	@Autowired
	private EventDao eventDao;

	@Autowired
	private PasswordEncoder encoder;

	@Override
	public RegisterDTO registerUser(RegisterDTO request) {
		User user = new User();
		user.setEmail(request.getEmail());
		user.setPassword(encoder.encode(request.getPassword()));// set encoded pwd
		user.setDob((request.getDob()));
		user.setAccountNumber(request.getAccountNumber());
		user.setAdharNumber(request.getAdharNumber());
		user.setContactNumber(request.getContactNumber());
		user.setName(request.getName());
		user.setRole(request.getRole());
		user.setSalary(request.getSalary());
		User persistentUser = userDao.save(user);
		String h="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "<!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "  <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG/>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "  </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]-->\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
				+ "  <title></title>\r\n"
				+ "  \r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "      @media only screen and (min-width: 570px) {\r\n"
				+ "  .u-row {\r\n"
				+ "    width: 550px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    vertical-align: top;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col-100 {\r\n"
				+ "    width: 550px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "@media (max-width: 570px) {\r\n"
				+ "  .u-row-container {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    padding-left: 0px !important;\r\n"
				+ "    padding-right: 0px !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    display: block !important;\r\n"
				+ "  }\r\n"
				+ "  .u-row {\r\n"
				+ "    width: calc(100% - 40px) !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "  .u-col > div {\r\n"
				+ "    margin: 0 auto;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "body {\r\n"
				+ "  margin: 0;\r\n"
				+ "  padding: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table,\r\n"
				+ "tr,\r\n"
				+ "td {\r\n"
				+ "  vertical-align: top;\r\n"
				+ "  border-collapse: collapse;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "p {\r\n"
				+ "  margin: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".ie-container table,\r\n"
				+ ".mso-container table {\r\n"
				+ "  table-layout: fixed;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "* {\r\n"
				+ "  line-height: inherit;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a[x-apple-data-detectors='true'] {\r\n"
				+ "  color: inherit !important;\r\n"
				+ "  text-decoration: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table, td { color: #000000; } @media (max-width: 480px) { #u_content_image_1 .v-container-padding-padding { padding: 30px 10px 10px !important; } #u_content_image_1 .v-src-width { width: auto !important; } #u_content_image_1 .v-src-max-width { max-width: 66% !important; } #u_content_image_2 .v-src-width { width: auto !important; } #u_content_image_2 .v-src-max-width { max-width: 55% !important; } }\r\n"
				+ "    </style>\r\n"
				+ "  \r\n"
				+ "  \r\n"
				+ "\r\n"
				+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #e0e5eb;color: #000000\">\r\n"
				+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
				+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
				+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #e0e5eb;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "  <tr style=\"vertical-align: top\">\r\n"
				+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
				+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #e0e5eb;\"><![endif]-->\r\n"
				+ "    \r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #000000;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: #000000;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_1\" style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:30px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/mqQjGK0/r661-Shubh-Karya-emblem-our.jpg\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 43%;max-width: 227.9px;\" width=\"227.9\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #9b0b01;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: #9b0b01;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:15px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h1 style=\"margin: 0px; color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: book antiqua,palatino; font-size: 35px;\">\r\n"
				+ "    Welcome, "+request.getName()+"\r\n"
				+ "  </h1>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <h3 style=\"margin: 0px; color: #ffffff; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: book antiqua,palatino; font-size: 18px;\">\r\n"
				+ "    You've Registered Successfully<br />Your Account Is Now Ready For Use\r\n"
				+ "  </h3>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #9b0b01;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: #9b0b01;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table id=\"u_content_image_2\" style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "  <tr>\r\n"
				+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
				+ "      \r\n"
				+ "      <img align=\"center\" border=\"0\" src=\"https://cdn.templates.unlayer.com/assets/1617644044941-sd.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 39%;max-width: 206.7px;\" width=\"206.7\" class=\"v-src-width v-src-max-width\"/>\r\n"
				+ "      \r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 40px 20px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #4b4a4a; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 20px; line-height: 28px; color: #fdec00;\">You can Login with your Respective Credentials</span></p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #000000;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: #000000;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 10px 15px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <div style=\"color: #7e8c8d; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"color: #f8f4f4; font-size: 14px; line-height: 19.6px;\">&copy; ShubhKaryaEvents. All Rights Reserved.</span></p>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
				+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 550px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;\">\r\n"
				+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
				+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:550px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "      \r\n"
				+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"550\" style=\"width: 550px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 550px;display: table-cell;vertical-align: top;\">\r\n"
				+ "  <div style=\"width: 100% !important;\">\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
				+ "  \r\n"
				+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "  <tbody>\r\n"
				+ "    <tr>\r\n"
				+ "      <td class=\"v-container-padding-padding\" style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
				+ "        \r\n"
				+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 0px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "    <tbody>\r\n"
				+ "      <tr style=\"vertical-align: top\">\r\n"
				+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
				+ "          <span>&#160;</span>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
				+ "    </td>\r\n"
				+ "  </tr>\r\n"
				+ "  </tbody>\r\n"
				+ "  </table>\r\n"
				+ "  <!--[if mso]></div><![endif]-->\r\n"
				+ "  <!--[if IE]></div><![endif]-->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>\r\n"
				+ "";
		try {
			mailservice.sendMail(request.getEmail(),"Shubhkarya Event Registration",h);
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		RegisterDTO dto = new RegisterDTO();
		System.out.println(persistentUser.toString());
		BeanUtils.copyProperties(persistentUser, dto);
		return dto;
	}

	@Override
	public String accessUsername(String email) {
		User u = userDao.findByEmail(email).orElseThrow();
		return u.getName();
	}

	@Override
	public List<User> getEmployees(String role) {
		if(role.equals("MANAGER")) {
			return userDao.findByRole("EMPLOYEE");	
		}
		else if(role.equals("MMANAGER")) {
			return userDao.findByRole("EMPLOYEE");	
		}
		else if(role.equals("MADMIN")) {
			return userDao.findByRole("MANAGER");	
		}else if(role.equals("viewcustomer")) {
			return userDao.findByRole("CUSTOMER");	
		}
		return userDao.findUserByRole();
	}

	@Override
	public void deleteEmployee(int id) {
		userDao.deleteById(id);

	}

	@Override
	public List<User> getEmployeesByEvent(int id) {
		Event e = eventDao.getById(id);
		return userDao.findByRoleAndRegevents("EMPLOYEE", e);
	}
	
	@Override
	public List<User> getManagersByEvent(int id) {
		Event e = eventDao.getById(id);
		return userDao.findByRoleAndRegevents("MANAGER", e);
	}

	@Override
	public int validateEmailAndGenearateOtp(String email) {
		int randomNumber;
		if (userDao.findByEmail(email).isPresent()) {
			randomNumber = (int) (Math.random() * 9999);
			if (randomNumber <= 1000) {
				randomNumber = randomNumber + 1000;
			}
		
			String html= "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
					+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
					+ "<head>\r\n"
					+ "<!--[if gte mso 9]>\r\n"
					+ "<xml>\r\n"
					+ "  <o:OfficeDocumentSettings>\r\n"
					+ "    <o:AllowPNG/>\r\n"
					+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
					+ "  </o:OfficeDocumentSettings>\r\n"
					+ "</xml>\r\n"
					+ "<![endif]-->\r\n"
					+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
					+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
					+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
					+ "  <!--[if !mso]><!--><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
					+ "  <title></title>\r\n"
					+ "  \r\n"
					+ "    <style type=\"text/css\">\r\n"
					+ "      @media only screen and (min-width: 620px) {\r\n"
					+ "  .u-row {\r\n"
					+ "    width: 600px !important;\r\n"
					+ "  }\r\n"
					+ "  .u-row .u-col {\r\n"
					+ "    vertical-align: top;\r\n"
					+ "  }\r\n"
					+ "\r\n"
					+ "  .u-row .u-col-50 {\r\n"
					+ "    width: 300px !important;\r\n"
					+ "  }\r\n"
					+ "\r\n"
					+ "  .u-row .u-col-100 {\r\n"
					+ "    width: 600px !important;\r\n"
					+ "  }\r\n"
					+ "\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "@media (max-width: 620px) {\r\n"
					+ "  .u-row-container {\r\n"
					+ "    max-width: 100% !important;\r\n"
					+ "    padding-left: 0px !important;\r\n"
					+ "    padding-right: 0px !important;\r\n"
					+ "  }\r\n"
					+ "  .u-row .u-col {\r\n"
					+ "    min-width: 320px !important;\r\n"
					+ "    max-width: 100% !important;\r\n"
					+ "    display: block !important;\r\n"
					+ "  }\r\n"
					+ "  .u-row {\r\n"
					+ "    width: calc(100% - 40px) !important;\r\n"
					+ "  }\r\n"
					+ "  .u-col {\r\n"
					+ "    width: 100% !important;\r\n"
					+ "  }\r\n"
					+ "  .u-col > div {\r\n"
					+ "    margin: 0 auto;\r\n"
					+ "  }\r\n"
					+ "}\r\n"
					+ "body {\r\n"
					+ "  margin: 0;\r\n"
					+ "  padding: 0;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "table,\r\n"
					+ "tr,\r\n"
					+ "td {\r\n"
					+ "  vertical-align: top;\r\n"
					+ "  border-collapse: collapse;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "p {\r\n"
					+ "  margin: 0;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ ".ie-container table,\r\n"
					+ ".mso-container table {\r\n"
					+ "  table-layout: fixed;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "* {\r\n"
					+ "  line-height: inherit;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "a[x-apple-data-detectors='true'] {\r\n"
					+ "  color: inherit !important;\r\n"
					+ "  text-decoration: none !important;\r\n"
					+ "}\r\n"
					+ "\r\n"
					+ "table, td { color: #000000; } a { color: #161a39; text-decoration: underline; } </style>\r\n"
					+ "  \r\n"
					+ "  \r\n"
					+ "\r\n"
					+ "<!--[if !mso]><!--><link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
					+ "\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #f9f9f9;color: #000000\">\r\n"
					+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
					+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
					+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #f9f9f9;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "  <tr style=\"vertical-align: top\">\r\n"
					+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
					+ "    <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #f9f9f9;\"><![endif]-->\r\n"
					+ "    \r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #f9f9f9;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f9f9f9;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f9f9f9;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "    <tbody>\r\n"
					+ "      <tr style=\"vertical-align: top\">\r\n"
					+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "          <span>&#160;</span>\r\n"
					+ "        </td>\r\n"
					+ "      </tr>\r\n"
					+ "    </tbody>\r\n"
					+ "  </table>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
					+ "  <tr>\r\n"
					+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
					+ "      \r\n"
					+ "      <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/mqQjGK0/r661-Shubh-Karya-emblem-our.jpg\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 29%;max-width: 168.2px;\" width=\"168.2\"/>\r\n"
					+ "      \r\n"
					+ "    </td>\r\n"
					+ "  </tr>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #161a39;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #161a39;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:35px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
					+ "  <tr>\r\n"
					+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"center\">\r\n"
					+ "    </td>\r\n"
					+ "  </tr>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 10px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"font-size: 14px; line-height: 140%; text-align: center;\"><span style=\"font-size: 28px; line-height: 39.2px; color: #ffffff; font-family: Lato, sans-serif;\">Please Reset Your Password </span></p>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #ffffff;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">Hello,</span></p>\r\n"
					+ "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\r\n"
					+ "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">We have sent you this email in response to your request to reset your password on ShubhKarya Events.</span></p>\r\n"
					+ "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\r\n"
					+ "<p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 18px; line-height: 25.2px; color: #666666;\">To reset your password, Please enter below OTP on our page : </span></p>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "<div align=\"center\">\r\n"
					+ "  <!--[if mso]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:'Lato',sans-serif;\"><tr><td style=\"font-family:'Lato',sans-serif;\" align=\"left\"><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"\" style=\"height:51px; v-text-anchor:middle; width:205px;\" arcsize=\"2%\" stroke=\"f\" fillcolor=\"#18163a\"><w:anchorlock/><center style=\"color:#FFFFFF;font-family:'Lato',sans-serif;\"><![endif]-->\r\n"
					+ "    <a href=\"\" target=\"_blank\" style=\"box-sizing: border-box;display: inline-block;font-family:'Lato',sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #FFFFFF; background-color: #18163a; border-radius: 1px;-webkit-border-radius: 1px; -moz-border-radius: 1px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;\">\r\n"
					+ "      <span style=\"display:block;padding:15px 40px;line-height:120%;\"><span style=\"font-size: 18px; line-height: 21.6px;\">"+String.valueOf(randomNumber)+"</span></span>\r\n"
					+ "    </a>\r\n"
					+ "  <!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:40px 40px 30px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"color: #888888; font-size: 14px; line-height: 19.6px;\"><em><span style=\"font-size: 16px; line-height: 22.4px;\">Please ignore this email if you did not request a password change.</span></em></span><br /><span style=\"color: #888888; font-size: 14px; line-height: 19.6px;\"><em><span style=\"font-size: 16px; line-height: 22.4px;\">&nbsp;</span></em></span></p>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #18163a;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #18163a;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"300\" style=\"width: 300px;padding: 20px 20px 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 20px 20px 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 16px; line-height: 22.4px; color: #ecf0f1;\">Contact :</span></p>\r\n"
					+ "<span style=\"font-size: 14px; line-height: 19.6px; color: white;\">shubhkaryaaevents.off@gmail.com</span></p>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"300\" style=\"width: 300px;padding: 0px 0px 0px 20px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-50\" style=\"max-width: 320px;min-width: 300px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px 0px 0px 20px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "<div align=\"left\">\r\n"
					+ "  <div style=\"display: table; max-width:187px;\">\r\n"
					+ "  <!--[if (mso)|(IE)]><table width=\"187\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse;\" align=\"left\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:187px;\"><tr><![endif]-->\r\n"
					+ "  \r\n"
					+ "    \r\n"
					+ "    \r\n"
					+ "    \r\n"
					+ "    \r\n"
					+ "    <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    <p style=\"line-height: 140%; font-size: 14px;\"><span style=\"font-size: 14px; line-height: 19.6px;\"><span style=\"color: #ecf0f1; font-size: 14px; line-height: 19.6px;\"><span style=\"line-height: 19.6px; font-size: 14px;\">&copy; ShubhKaryaEvents. All Rights Reserved.</span></span></span></p>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: #f9f9f9\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #1c103b;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: #f9f9f9;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #1c103b;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:15px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #1c103b;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "    <tbody>\r\n"
					+ "      <tr style=\"vertical-align: top\">\r\n"
					+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
					+ "          <span>&#160;</span>\r\n"
					+ "        </td>\r\n"
					+ "      </tr>\r\n"
					+ "    </tbody>\r\n"
					+ "  </table>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
					+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f9f9f9;\">\r\n"
					+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
					+ "      <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #f9f9f9;\"><![endif]-->\r\n"
					+ "      \r\n"
					+ "<!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
					+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
					+ "  <div style=\"width: 100% !important;\">\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--><div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
					+ "  \r\n"
					+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
					+ "  <tbody>\r\n"
					+ "    <tr>\r\n"
					+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px 30px 20px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
					+ "        \r\n"
					+ "  <div style=\"line-height: 140%; text-align: left; word-wrap: break-word;\">\r\n"
					+ "    \r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "      </td>\r\n"
					+ "    </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "</table>\r\n"
					+ "\r\n"
					+ "  <!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "<!--[if (mso)|(IE)]></td><![endif]-->\r\n"
					+ "      <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "</div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "    <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
					+ "    </td>\r\n"
					+ "  </tr>\r\n"
					+ "  </tbody>\r\n"
					+ "  </table>\r\n"
					+ "  <!--[if mso]></div><![endif]-->\r\n"
					+ "  <!--[if IE]></div><![endif]-->\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>\r\n"
					+ "";
			try {
				mailservice.sendMail(email,"Password Reset OTP",html);
			} catch (MessagingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			return randomNumber;
		}
		else {
			return -1;
		}
	}

	@Override
	public boolean changePassword(String email, String password) {
		User u=userDao.findByEmail(email).orElseThrow();
		u.setPassword(encoder.encode(password));
		if(userDao.save(u)!=null)
			return true;
		return false;
	}

	@Override
	public User viewOwnDetails(String email) {
		User u = userDao.findByEmail(email).orElseThrow();
		return u;
	}
}
